yujincheng08/BiliRoaming

app/src/main/java/me/iacn/biliroaming/MainActivity.kt, app/src/main/java/me/iacn/biliroaming/XposedInit.kt, app/src/main/java/me/iacn/biliroaming/XposedResInit.kt, app/src/main/java/me/iacn/biliroaming/hook/BangumiPlayUrlHook.kt, app/src/main/res/xml/prefs_setting.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties
RT, and I also update the Gradle & reformat code.
@yujincheng08
=> [ Fixed ] App crash if user not select beautify_splash.

app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml, gradle.properties
=> Purify Channel

app/src/main/java/me/iacn/biliroaming/SettingDialog.kt, app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt, app/src/main/java/me/iacn/biliroaming/model/BottomItem.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> Customize Bottom Bar

app/src/main/java/me/iacn/biliroaming/SettingDialog.kt, app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> Customize Bottom Bar Fixed

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/SettingDialog.kt, app/src/main/java/me/iacn/biliroaming/XposedInit.kt, app/src/main/java/me/iacn/biliroaming/hook/MusicNotificationHook.kt, app/src/main/java/me/iacn/biliroaming/hook/ijkhook.kt, app/src/main/res/layout/cutomize_danmaku_config_dialog.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
先不要关 #92 ，还有一小点问题，比如弹幕速度不会随默认播放速度改变，需要手动切换一次播放速度  
单独开一个 ijkhook 的文件是因为找不到合适的地方，且要写的东西还挺多随便塞到别的文件里感觉不是很好。日后还有一些东西要放到这里，比如 #92 的“阻止弹幕速度随播放速度变化”和 #93 的设置默认清晰度
=> custom playback speed

app/src/main/java/me/iacn/biliroaming/network/BiliRoamingApi.kt
=> 添加使用泰区 api 获取 season

app/src/main/java/me/iacn/biliroaming/utils/Log.kt
=> Fix toast again

app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
1. 在首页标签添加大陆/港澳台影视分页
2. 修复台湾ip未显示影视分页(开启上面的开关才生效)
=> 在首页标签添加大陆/港澳台影视分页

app/src/main/java/me/iacn/biliroaming/SettingDialog.kt, app/src/main/java/me/iacn/biliroaming/hook/PegasusHook.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
添加关键词过滤首页推送
修复 隐藏首页低播放量视频 没有输入任何内容点击确定时崩溃的bug
=> 添加关键词过滤首页推送

app/src/main/java/me/iacn/biliroaming/SettingDialog.kt, app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt
1. 修复自定义底栏（如果之前设置了自定义底栏，需要重新设置）
2. 修复概念版影视标签位置问题 #169
=> 修复两个bug（如果之前设置了自定义底栏，需要重新设置）

app/src/main/java/me/iacn/biliroaming/SettingDialog.kt, app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> Add Channel Button at the bottom

app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt
=> Remove Channel Button at the top-right when add it at the bottom

app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> Purify Space

app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt, app/src/main/res/values/arrays.xml
Purify cheese tab in UP's space
净化UP空间的课堂分页
=> Purify cheese tab in UP's space

app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt
1. 官方变更港澳台影视uri，并且改名为「影劇」
2. 将 reportId 改为官方使用的名称
3. 加了一点注释，希望能给以后改代码的人方便一点
=> Change film uri

app/src/main/java/me/iacn/biliroaming/network/BiliRoamingApi.kt
`ep.put("status", 2)`
`"status": 13` prevent normal user from cache download
=> Fix thailand cache download

app/src/main/java/me/iacn/biliroaming/hook/BangumiSeasonHook.kt, app/src/main/java/me/iacn/biliroaming/network/BiliRoamingApi.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
1. 添加「开启其它地区影剧搜索」
2. 原本「开启其它地区番剧搜索」已修改。如果原本打开的，需要重新打开。
=> 添加其它地区影剧搜索（原本番剧搜索，需要重新打开）

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/XposedInit.kt, app/src/main/java/me/iacn/biliroaming/hook/RecommendHook.kt, app/src/main/java/me/iacn/biliroaming/hook/UpperAdHook.kt, app/src/main/res/xml/prefs_setting.xml
=> 修复破烂 UpperAdHook

app/build.gradle.kts, app/proguard-rules.pro
https://mbonnin.medium.com/the-different-kotlin-stdlibs-explained-83d7c6bf293
=> Remove kotlin stdlib jdk7&8

app/src/main/java/me/iacn/biliroaming/HomeFilterDialog.kt
=> Set "hide low play recommend" default to 0

app/src/main/res/layout/home_filter_dialog.xml
Fix https://t.me/biliroaming_chat/596628
=> add ScrollView in home_filter_dialog

app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt
fix https://t.me/biliroaming_chat/598404
=> fix customize drawer

app/src/main/java/me/iacn/biliroaming/utils/Log.kt, app/src/main/java/me/iacn/biliroaming/utils/Utils.kt
fallback to normal Toast if ToastHelper doesn't exist
=> Use ToastHelper to show Toast

app/src/main/java/me/iacn/biliroaming/SettingDialog.kt, app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt, app/src/main/res/layout/custom_button.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
1. 自定义 Scheme 链接
2. 在【我的】页面添加自定义按钮
=> open custom URI scheme link

app/src/main/java/me/iacn/biliroaming/SettingDialog.kt
客户端版本：6.66.0    (release-b8172571)
漫游版本：1.6.0  (加上自己改了底下这段代码)
LSPatch (commit 34000e3ecee8ddc8cab50fcc7b7e7ee0c02c9759)
=> custom theme can use in 6.66.0

app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> Add Korean Variety Show tab in home page

app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> Remove unavailable upos host

app/src/main/java/me/iacn/biliroaming/DynamicFilterDialog.kt, app/src/main/java/me/iacn/biliroaming/SettingDialog.kt, app/src/main/java/me/iacn/biliroaming/hook/DynamicHook.kt, app/src/main/java/me/iacn/biliroaming/utils/Utils.kt, app/src/main/res/values/arrays.xml
- 抛弃分隔符，优化动态过滤器输入体验
- 修复某些情况下根据内容关键字动态不能被移除的问题
=> Throw away seperator and fix dynamic remove not completely

app/src/main/java/me/iacn/biliroaming/DynamicFilterDialog.kt, app/src/main/java/me/iacn/biliroaming/XposedInit.kt, app/src/main/java/me/iacn/biliroaming/hook/DynamicHook.kt, app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt, app/src/main/java/me/iacn/biliroaming/hook/MusicNotificationHook.kt, app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> Add some purify features

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/network/BiliRoamingApi.kt, app/src/main/proto/me/iacn/biliroaming/configs.proto
=> feat: support brotli compression

app/src/main/java/me/iacn/biliroaming/DynamicFilterDialog.kt, app/src/main/java/me/iacn/biliroaming/HomeFilterDialog.kt, app/src/main/java/me/iacn/biliroaming/SettingDialog.kt, app/src/main/java/me/iacn/biliroaming/SpeedTestDialog.kt, app/src/main/java/me/iacn/biliroaming/hook/SettingHook.kt
并不建议使用 moduleRes 获取模块资源，当 Configuration 改变时，例如
APP 打开时，这时切换系统首选语言后，moduleRes 的 Configuration 并不
会得到更新
=> Fix crash when system restore activity state

app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt
=> fix bug in #649

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/XposedInit.kt, app/src/main/java/me/iacn/biliroaming/hook/PlayArcConfHook.kt, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
一开始只想着干后台播放，后来发现投屏限制也可以干掉就顺手干掉了，于是这个 `key` 有点诡异，等我明天清醒点再想想叫啥，或者有谁给点建议也行
测试视频：<https://www.bilibili.com/video/av513189870>
---
<details>
<summary>调试用</summary>
```java
//        "com.bilibili.video.videodetail.player.VideoDetailPlayer".findClass(lpparam.classLoader).hookAfterMethod("q1") { param ->
//            Log.v("114514: VDP.q1 result ${param.result}")
//        }
//        "com.bilibili.video.videodetail.player.VideoDetailPlayer".findClass(lpparam.classLoader).hookAfterMethod("F0") { param ->
//            Log.v("114514: VDP.F0 result ${param.result}")
//        }
//        "tv.danmaku.bili.videopage.player.UgcPlayerFragment".findClass(lpparam.classLoader).hookAfterMethod("q1") { param ->
//            Log.v("114514: UPF.q1 result ${param.result}")
//        }
// …
```
=> 添加 强制允许后台播放和投屏

app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt
- 修复 自定义我的页面 选项 (`Int` --> `Long`)
=> fix: get section list

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/BangumiSeasonHook.kt, app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> Add block comment keyword search support

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/ReplaceStoryHook.kt
Fix replace story video by replace uri.
old: hook onCreate when start video activity.
new: change "bilibili://story/" to "bilibili://video/" when get the url.
=> Fix replace story video

app/src/main/java/me/iacn/biliroaming/hook/CopyHook.kt, app/src/main/java/me/iacn/biliroaming/utils/Utils.kt
=> Unified free copy dialog style

app/src/main/java/me/iacn/biliroaming/XposedInit.kt, app/src/main/java/me/iacn/biliroaming/hook/AllowMiniPlayHook.kt, app/src/main/java/me/iacn/biliroaming/hook/BangumiPlayUrlHook.kt, app/src/main/proto/me/iacn/biliroaming/api.proto, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> Allow unlocked bangumi small window playing

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/BangumiSeasonHook.kt, app/src/main/proto/me/iacn/biliroaming/api.proto
=> Fix other area bangumi search

app/src/main/res/values/strings.xml
=> Make simplified Chinese correspond to traditional Chinese

app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
例如：https://www.bilibili.com/video/BV1rV4y1p7tZ?t=82
=> Allow block up recommend ads

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/CopyHook.kt, app/src/main/proto/me/iacn/biliroaming/configs.proto
=> Fix comment free copy

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/CopyHook.kt, app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt, app/src/main/proto/me/iacn/biliroaming/configs.proto, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
=> Support private letter free copy

app/src/main/java/me/iacn/biliroaming/SettingDialog.kt, app/src/main/java/me/iacn/biliroaming/hook/SubtitleHook.kt, app/src/main/java/me/iacn/biliroaming/utils/Utils.kt
=> Force showing close subtitle option

app/src/main/java/me/iacn/biliroaming/hook/BangumiSeasonHook.kt, app/src/main/proto/me/iacn/biliroaming/api.proto
=> Update `SearchBangumiCard` proto

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/LiveRoomHook.kt, app/src/main/proto/me/iacn/biliroaming/configs.proto, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> Allow disable live room switching

app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
=> Support purify contract card

app/src/main/java/me/iacn/biliroaming/DynamicFilterDialog.kt, app/src/main/java/me/iacn/biliroaming/HomeFilterDialog.kt, app/src/main/java/me/iacn/biliroaming/hook/DynamicHook.kt, app/src/main/java/me/iacn/biliroaming/hook/PegasusHook.kt, app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt, app/src/main/java/me/iacn/biliroaming/utils/Utils.kt, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
=> Support regex match on home & dynamic filter

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt, app/src/main/java/me/iacn/biliroaming/hook/LiveRoomHook.kt, app/src/main/res/values-zh-rTW/arrays.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> Purify live room popups & disable double click to like

app/src/main/java/me/iacn/biliroaming/SettingDialog.kt, app/src/main/java/me/iacn/biliroaming/hook/DynamicHook.kt, app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt, app/src/main/res/layout/custom_button.xml, app/src/main/res/layout/custom_subtitle_dialog.xml, app/src/main/res/layout/dialog_argb_color_choose.xml, app/src/main/res/layout/dialog_color_choose.xml
- 修复hd版本搜索净化
- 修复hd版本直播间浮窗净化
- 部分布局外套ScrollView，优化hd版本在手机上的使用体验
- 优化动态过滤
=> Compatible with newest hd ver

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
Tested in:
`com.bilibili.app.in` `3.16.0` `7082100`
`com.bilibili.app.blue` `7.5.4` `7054100`
`tv.danmaku.bili` `7.9.0` `7090300`
fix #890
=> fix: theme helper

.github/workflows/PR.yml, .github/workflows/android.yml
ref: https://github.com/actions/cache/blob/main/examples.md#java---gradle
=> fix: actions cache

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
=> Fix generate chs subtitle

app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt
=> fix: th ep is not playable (flagged as removed)

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
=> Fix auto like

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/XposedInit.kt, app/src/main/java/me/iacn/biliroaming/hook/BlockUpdateHook.kt, app/src/main/proto/me/iacn/biliroaming/configs.proto, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> Block app update

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/XposedInit.kt, app/src/main/java/me/iacn/biliroaming/hook/VipSectionHook.kt, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> Remove vip section

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/XposedInit.kt, app/src/main/java/me/iacn/biliroaming/hook/CommentImageHook.kt, app/src/main/proto/me/iacn/biliroaming/configs.proto, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> Save comment images

app/src/main/java/me/iacn/biliroaming/hook/CommentImageHook.kt, app/src/main/java/me/iacn/biliroaming/hook/WebViewHook.kt
=> Implement `saveImage` bridge api

app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
fix: #987
移除视频下方合集列表
自己提的功能自己写.png
=> feat: remove_video_UgcSeason

app/src/main/java/me/iacn/biliroaming/HomeFilterDialog.kt, app/src/main/java/me/iacn/biliroaming/hook/PegasusHook.kt
=> Regex match on up name

app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt
Tests: https://www.bilibili.com/video/BV18g4y1W7Nk
=> Fix remove video guide popups

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/XposedInit.kt, app/src/main/java/me/iacn/biliroaming/hook/P2pHook.kt, app/src/main/proto/me/iacn/biliroaming/configs.proto, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> feat: remove PCDN support

app/src/main/java/me/iacn/biliroaming/XposedInit.kt, app/src/main/java/me/iacn/biliroaming/hook/MainPageStoryHook.kt, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
修改点击首页头像为跳转到个人主页
Fix https://github.com/yujincheng08/BiliRoaming/issues/700
=> feat: disable MainPageStory

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/XposedInit.kt, app/src/main/java/me/iacn/biliroaming/hook/BangumiPlayUrlHook.kt, app/src/main/java/me/iacn/biliroaming/hook/VideoQualityHook.kt, app/src/main/jni/biliroaming.cc, app/src/main/proto/me/iacn/biliroaming/configs.proto, app/src/main/res/values-zh-rTW/arrays.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> Allow custom video default quality

app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
移除视频内的荣誉榜 (入站必刷、每周必看、全站排行榜、4K频道精选等)
=> feat: remove_video_Honor

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
=> Fix save comment images for 7.25.0+

app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt, app/src/main/res/values-zh-rTW/arrays.xml, app/src/main/res/values/arrays.xml
=> Purify more live room popups

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/P2pHook.kt, app/src/main/proto/me/iacn/biliroaming/configs.proto, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
优化阻止直播通过 P2P 上传/下载, 优化阻止视频通过 IP:Port 型的 PCDN 加载. 已在7.24, 6.80版本测试通过, 效果良好. 
没有其他问题可merge
=> feat: optimize pcdn block

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/PlayArcConfHook.kt
=> Fix unlock play limit

app/src/main/java/me/iacn/biliroaming/hook/BangumiSeasonHook.kt, app/src/main/java/me/iacn/biliroaming/hook/DanmakuHook.kt, app/src/main/java/me/iacn/biliroaming/hook/PlayArcConfHook.kt, app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt, app/src/main/java/me/iacn/biliroaming/utils/Utils.kt, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/strings_raw.xml, app/src/main/res/xml/prefs_setting.xml
Fix #1039 and refine some codes
=> Block comment guide

app/src/main/java/me/iacn/biliroaming/hook/SubtitleHook.kt
=> Fix add close subtitle

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/CustomThemeHook.kt, app/src/main/java/me/iacn/biliroaming/utils/KotlinXposedHelper.kt, app/src/main/java/me/iacn/biliroaming/utils/Utils.kt, app/src/main/jni/biliroaming.cc, app/src/main/proto/me/iacn/biliroaming/configs.proto
=> Fix custom theme

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt, app/src/main/java/me/iacn/biliroaming/hook/SubtitleHook.kt, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
在移除互动浮窗的基础上, 将其他浮窗一并移除, 包括跳转其他应用, 以及 "开电视 看 B 站 TV 版" 等.
=> feat: purify videoGuide

app/src/main/java/me/iacn/biliroaming/DynamicFilterDialog.kt, app/src/main/java/me/iacn/biliroaming/hook/DynamicHook.kt, app/src/main/res/values-zh-rTW/arrays.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml
=> Enhance purify dynamic

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/DynamicHook.kt, app/src/main/java/me/iacn/biliroaming/hook/PegasusHook.kt, app/src/main/java/me/iacn/biliroaming/utils/Utils.kt, app/src/main/proto/me/iacn/biliroaming/configs.proto, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
=> Long press home card to add filter keyword

app/src/main/java/me/iacn/biliroaming/hook/DynamicHook.kt
修复开启屏蔽无权查看动态(例如充电专属)后动态无法正常加载/刷新的问题.
=> Fix purify onlyfans dynamic

app/src/main/java/me/iacn/biliroaming/hook/PegasusHook.kt, app/src/main/java/me/iacn/biliroaming/utils/KotlinXposedHelper.kt, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> Disable home page auto refresh

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/XposedInit.kt, app/src/main/java/me/iacn/biliroaming/hook/PublishToFollowingHook.kt, app/src/main/proto/me/iacn/biliroaming/configs.proto, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> Disable auto select following to dynamic

app/src/main/java/me/iacn/biliroaming/BaseWidgetDialog.kt, app/src/main/java/me/iacn/biliroaming/DynamicFilterDialog.kt, app/src/main/java/me/iacn/biliroaming/HomeFilterDialog.kt, app/src/main/java/me/iacn/biliroaming/hook/DynamicHook.kt, app/src/main/java/me/iacn/biliroaming/hook/PegasusHook.kt, app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
=> Apply home filter to video relates

app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt
=> Fix block video guide

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/CommentImageHook.kt, app/src/main/proto/me/iacn/biliroaming/configs.proto, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
新版本这一块改用 Jetpack Compose，很难直接添加长按事件，
因此需要点开后长按预览图片保存
=> Fix save comment images for 7.29.0+

app/src/main/java/me/iacn/biliroaming/hook/BangumiPlayUrlHook.kt
=> Fix unlock area limit for playViewUnite

app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt, app/src/main/java/me/iacn/biliroaming/hook/WebViewHook.kt, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> Block video comments

app/src/main/java/me/iacn/biliroaming/hook/BangumiPlayUrlHook.kt, app/src/main/java/me/iacn/biliroaming/hook/UposReplaceHook.kt, app/src/main/java/me/iacn/biliroaming/utils/UposReplaceHelper.kt
=> refine PCDN replace

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/VideoQualityHook.kt
fix: 修改半屏清晰度(7.39.0+)  
fix #1177
=> fix: hook player preload

app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> feat: block live order

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
修复 7.40.0+ playerCoreService 找不到的问题
影响范围: 视频默认播放速度等
=> fix: fail to find playerCoreService

app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
移除视频详情页 UP 名字旁出现的的大会员标识(7.40.0+)
See https://t.me/biliroaming_chat/2116721
=> feat: remove up vip label on 7.40.0+

app/src/main/java/me/iacn/biliroaming/hook/CopyHook.kt
fix: 长按自由复制无论是否开启总是启用的问题(`1cab2b9` 引入)
=> fix: enhance long click copy

app/src/main/java/me/iacn/biliroaming/hook/SubtitleHook.kt, app/src/main/java/me/iacn/biliroaming/utils/Utils.kt
#1205 引入的系列问题修复 / 7.43.0 兼容问题修复
=> fix: unexpected danmaku close when unlock bangumi

app/src/main/java/me/iacn/biliroaming/hook/StartActivityHook.kt
=> fix: replace story mode video

app/src/main/java/me/iacn/biliroaming/hook/PegasusHook.kt, app/src/main/res/values-zh-rTW/arrays.xml, app/src/main/res/values/arrays.xml
=> feat: purify main feed cm

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/VideoQualityHook.kt, app/src/main/proto/me/iacn/biliroaming/configs.proto
修复自定义半屏清晰度在新版本失效的问题
(上次集中修 bug 漏了这个, 主要是不太能看得出来)
=> fix: custom half screen video quality

app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt
=> fix: purify search referral

app/src/main/java/me/iacn/biliroaming/hook/PegasusHook.kt, app/src/main/java/me/iacn/biliroaming/utils/KotlinXposedHelper.kt, app/src/main/res/values-zh-rTW/arrays.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
允许自定义首页推荐封面比例(4:3 或 16:9) #1198
=> feat: custom pegasus cover ratio

app/src/main/java/me/iacn/biliroaming/DynamicFilterDialog.kt, app/src/main/java/me/iacn/biliroaming/hook/DynamicHook.kt, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
=> feat: filter ad link dynamic

app/src/main/java/me/iacn/biliroaming/hook/DynamicHook.kt
fix: dynamic prefer video tab #1252
=> fix: 7.45.0+ compatibility

app/src/main/java/me/iacn/biliroaming/CommentFilterDialog.kt, app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt, app/src/main/res/values/strings.xml
=> feat: support filter comment base on author level

app/src/main/java/me/iacn/biliroaming/SettingDialog.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
支持复制 access_key，方便导出给各类 API 库使用
=> feat: copy access_key

app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> feat: no live mask

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/XposedInit.kt, app/src/main/java/me/iacn/biliroaming/hook/KillDelayBootHook.kt
Kill ff_boot_exp_delay_xxx from cloud control in com.bilibili.gripper.exp.a$a
=> feat: KillDelayBootHook

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/CopyHook.kt, app/src/main/proto/me/iacn/biliroaming/configs.proto
issue: [#1460](https://github.com/yujincheng08/BiliRoaming/issues/1460)
=> fix: comment copy on play v3.19.1+ and v7.77.0+

app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt, app/src/main/res/values-zh-rTW/arrays.xml, app/src/main/res/values/arrays.xml
=> fix: home tab filter adds rules for bangumi_v2 and cinema_v2

app/src/main/java/me/iacn/biliroaming/hook/BangumiPlayUrlHook.kt, app/src/main/java/me/iacn/biliroaming/hook/BangumiSeasonHook.kt, app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt
v8.17.0+达到勉强能用级别，仍然有不完善的地方（选集切其他弹不支持观看）
=> fix: BangumiPlayUrlHook, BangumiSeasonHook, ProtoBufHook for v8.17.0+

app/src/main/java/me/iacn/biliroaming/hook/PegasusHook.kt
=> feat: PegasusHook support viewUnite

app/src/main/java/me/iacn/biliroaming/SearchFilterDialog.kt, app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
=> feat: search filter add remove relate promote

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/BangumiPlayUrlHook.kt, app/src/main/java/me/iacn/biliroaming/hook/BangumiSeasonHook.kt, app/src/main/java/me/iacn/biliroaming/hook/PegasusHook.kt, app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt
fix blockVideoComment
fix bangumiPlayUrlHook for hk, tw, thai, cn
重构 精简代码
修复 屏蔽视频评论区
修复 港澳台泰大陆区的番剧观看
=> refactor: optimize code

app/src/main/java/me/iacn/biliroaming/hook/DynamicHook.kt
=> fix: incorrect method name

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/BangumiPlayUrlHook.kt, app/src/main/java/me/iacn/biliroaming/hook/DynamicHook.kt
- 修复动态页首选视频标签
- 修复视频简介自由复制
- 修复允许下载
只在粉版v8.27.0和play版v3.20.0上测试可用
=> fix: prefer video tab & copy video description & allow download

app/src/main/java/me/iacn/biliroaming/hook/ShareHook.kt, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
=> fix: replace b23.tv with bili2233.cn

app/src/main/java/me/iacn/biliroaming/hook/DynamicHook.kt, app/src/main/java/me/iacn/biliroaming/hook/MusicNotificationHook.kt
- 修复强制媒体通知为原生样式 #1590
- 修复净化动态视频页 #1573
=> fix: force media notification styles follow the system & purify dyn video page

app/src/main/java/me/iacn/biliroaming/DynamicFilterDialog.kt, app/src/main/java/me/iacn/biliroaming/hook/DynamicHook.kt, app/src/main/res/values/strings.xml
=> feat: separately purify Live and UP in dyn all page

app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
=> fix: change the description for purify share

app/src/main/java/me/iacn/biliroaming/hook/BangumiPlayUrlHook.kt
=> fix: crash caused by unlocking area in some cases

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/VideoQualityHook.kt, app/src/main/proto/me/iacn/biliroaming/configs.proto
=> fix: video quality for v8.9.0+

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/AutoLikeHook.kt, app/src/main/java/me/iacn/biliroaming/hook/PegasusHook.kt, app/src/main/java/me/iacn/biliroaming/hook/PlayArcConfHook.kt, app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt, app/src/main/proto/me/iacn/biliroaming/configs.proto
=> fix: auto like & remove relate video

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/SettingDialog.kt, app/src/main/java/me/iacn/biliroaming/hook/CustomThemeHook.kt
=> fix: find selectQuality and disable custom theme for hd ver.

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/TryWatchVipQualityHook.kt, app/src/main/proto/me/iacn/biliroaming/configs.proto
=> fix: disable try vip quality for v7.50.0+

app/src/main/java/me/iacn/biliroaming/hook/BangumiPlayUrlHook.kt
=> fix: crash in some cases

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/XposedInit.kt, app/src/main/java/me/iacn/biliroaming/hook/LiveQualityHook.kt, app/src/main/proto/me/iacn/biliroaming/configs.proto, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> feat: live quality

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/LiveQualityHook.kt, app/src/main/proto/me/iacn/biliroaming/configs.proto
=> fix: refine live quality

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/StartActivityHook.kt
对于 #1576 提供旧版兼容处理，使替换竖版视频能在没有新版播放器的版本正常工作
=> compat: replaceStoryVideo on old versions

app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt, app/src/main/java/me/iacn/biliroaming/utils/Utils.kt
=> feat: hide livetip

app/src/main/java/me/iacn/biliroaming/hook/VipSectionHook.kt
版本 8.52.0 release-b19582068 粉 Play
=> fix: VipSectionHook
