app/src/main/java/me/iacn/biliroaming/hook/CoverHook.kt
具体崩溃见 [log.txt](https://github.com/yujincheng08/BiliRoaming/files/5911965/log.txt)，1723 行附近
判断是否存在好像很麻烦，就直接「先存，出错再说」了（
以及，这样的话保存失败的 Toast 好像会一闪而过？这个不知道怎么修
=> 修复 重复保存封面导致崩溃

app/src/main/java/me/iacn/biliroaming/utils/Log.kt
setText 和 show 好像不会重新计时，所以连续的两个 Toast 实际上时间是从前一个开始算的
要复用那个 Toast 对象的话网上的解决方案都是 cancel 然后重新 makeText，感觉意义不大
=> 解决 Toast 一闪而过 的问题

app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt
修复港澳台用戶，"净化首页标签"开启"其他"选项时，会导致"动画"标签同时被屏蔽。
=> 修复港澳台用戶，"净化首页标签"开启"其他"选项时，会导致"动画"标签同时被屏蔽。

app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt, app/src/main/res/values/strings.xml
1. 复原修改，并新增一个判断(当隐藏功能未开启时，才会自动隐藏底栏的“我的”)。 https://github.com/yujincheng08/BiliRoaming/commit/bdb002318d371b35d5a1d7e72c4fb540e891475c#diff-a8bc9a856457fa0468f8780b2fcb555398743d4ffe7ce30e851f3af956ef78aaL75-L82
2. 在描述中，提供复原时出现问题解决方法。
3. 删除没用的 strings。
=> Add description for cancel “移动我的页面到侧边栏”

app/src/main/res/xml/prefs_setting.xml
在过去的版本中，出差账号默认修复，无需开启任何开关。
而在 fix_space 这一提交之后，需要开启开关才可修复出差账号。可以预想到，正式版发布后肯定会有若干人提问“为什么更新之后出差打不开了”之类的问题。
并且此功能开启选项位置偏后，也有部分新用户注意不到这个选项（或者不知道出差账户也是受限的）
=> 默认开启 修复UP主空间 功能

app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt
修复 自定义我的页面 bug：
　　保留 标题游戏中心，却不保留底下任意一个标题项目，导致漫游设置消失。
=> Fix custom drawer bug

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/BangumiSeasonHook.kt
~~`kotlin.Pair`由于漫游也用了，并且被混淆，故比较时使用类名比较。~~
人傻了，本来就不是framework里面的。
=> Fix th comment invalid tips again

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/StartActivityHook.kt
又把 `BangumiCommentInvalidFragmentV2` 类加回来了，然而并没有使用，故调整了下查找先后顺序。
=> Fix th comment invalid tips

app/src/main/java/me/iacn/biliroaming/XposedInit.kt, app/src/main/java/me/iacn/biliroaming/hook/PlayerLongPressHook.kt, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
在通过播放器主界面**微调**进度时，极易误触发长按加速，播放器编辑界面无关闭长按加速的选项。
若无长按加速播放的需求，可通过此法禁用此功能。
=> Allow to disable player long click to accelerate

app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt
直播间相关接口没有用 `BiliCall` 默认配置的 `BiliConverterFactory` 获取 Converter，自定义了一个名叫 `JsonNullListParser` 的 Converter。
=> Fix purify live shopping info

app/src/main/java/me/iacn/biliroaming/Constant.kt, app/src/main/java/me/iacn/biliroaming/XposedInit.kt
`client_info` 接口某些网络下有可能拿不到 IP 地理位置信息，进而导致测速失败等问题，`zone` 接口作为备用手段。
=> Fix get current area info

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/BangumiPageAdHook.kt, app/src/main/java/me/iacn/biliroaming/hook/BangumiPlayUrlHook.kt, app/src/main/java/me/iacn/biliroaming/hook/BangumiSeasonHook.kt, app/src/main/java/me/iacn/biliroaming/hook/CopyHook.kt, app/src/main/java/me/iacn/biliroaming/hook/JsonHook.kt, app/src/main/java/me/iacn/biliroaming/hook/PegasusHook.kt, app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt, app/src/main/java/me/iacn/biliroaming/hook/SubtitleHook.kt, app/src/main/java/me/iacn/biliroaming/network/BiliRoamingApi.kt, app/src/main/java/me/iacn/biliroaming/utils/Utils.kt, app/src/main/proto/me/iacn/biliroaming/api.proto, app/src/main/proto/me/iacn/biliroaming/configs.proto, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
fix: 哔哩哔哩粉版 7.41.0+ 由于 API 变动等因素产生的大量问题 #1199
仅在粉版测试, HD 版, Play 版未测试, 有问题另外修复.
=> fix: 7.41.0 compatibility

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/MusicNotificationHook.kt, app/src/main/java/me/iacn/biliroaming/hook/SpeedHook.kt, app/src/main/proto/me/iacn/biliroaming/configs.proto
修复新版 APP 自定义默认播放速度出现的下列问题: 
- APP 复用 ijkplayer 时, 默认播放速度不生效, 如合集/分P间切换等场景
- 使用新版本播放器时, 无法手动设置 1 倍速(实际已设置为 1 倍速, 但仍显示为自定义的默认播放速度)
=> fix: default playback speed on 7.41.0+

app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt
彻底移除竖版视频 (story mode)的入口
refactor: remove old way to replace story
=> fix: replace story mode video entirely

app/src/main/java/me/iacn/biliroaming/hook/ShareHook.kt
在不添加 unique_k 的情况下, 视频在移动端网页里无法直接播放
随机添加 unique_k 使得视频可以直接播放
=> feat: add unique_k parameter to share

app/src/main/java/me/iacn/biliroaming/SettingDialog.kt, app/src/main/java/me/iacn/biliroaming/XposedInit.kt, app/src/main/java/me/iacn/biliroaming/hook/MusicNotificationHook.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
=> feat: force system media controls

app/src/main/java/me/iacn/biliroaming/hook/CommentImageHook.kt
Change the path for saving comment images in the plugin to match the path used by the app.
=> Changing the path for saving the image

app/src/main/java/me/iacn/biliroaming/hook/BangumiSeasonHook.kt
在搜索一些敏感词时（比如“药娘”），会因为无法为navList插入元素导致崩溃
=> fix: crash when searching sensitive words

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
=> fix: initHookInfo find biliAccounts class failed on 8.18.0+

app/src/main/java/me/iacn/biliroaming/hook/StartActivityHook.kt
替换竖版视频功能使用新版activity，从而解决评论区图片打不开的问题
=> fix: use viewUnite for replaceStoryVideo

app/src/main/java/me/iacn/biliroaming/XposedInit.kt, app/src/main/java/me/iacn/biliroaming/hook/DynamicHook.kt, app/src/main/java/me/iacn/biliroaming/hook/KillDelayBootHook.kt, app/src/main/java/me/iacn/biliroaming/hook/PlayArcConfHook.kt, app/src/main/java/me/iacn/biliroaming/hook/SubtitleHook.kt, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_setting.xml
修复更多NoSuchMethodError
移除“禁止自动转到动态”功能，b站 v8.1x+ 起不会再自动勾选转发到动态，因此该功能没有存在的必要
=> fix: more NoSuchMethodError

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/CustomThemeHook.kt, app/src/main/java/me/iacn/biliroaming/hook/VideoQualityHook.kt
- 修复自定义主题
- 修复视频半屏/全屏清晰度
- 修复okio/okhttp的hookinfo
hookinfo那块我不知道我的理解有没有错，应该是要找到okio/okhttp包中的类吧
=> fix: custom theme & video quality & some hookinfo

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
- 修复okhttp的hookinfo
应该有部分功能能恢复正常（例如修复UP主空间）具体有哪些我也不清除。
=> fix: found wrong hookinfo of okhttp

app/src/main/java/me/iacn/biliroaming/hook/EnvHook.kt
=> fix: show avid

app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt, app/src/main/java/me/iacn/biliroaming/hook/PegasusHook.kt
- 修复play版全屏清晰度
本来以为play版已经修好了，但前几天发现全屏的时候会出现降到半屏设置的清晰度，但这功能我并不怎么用，再者当时已经在修自动点赞了，不想打断思路，就先晾一边了。
上个提交今天重新看了一下代码，发现我理解出了偏差，再加上脑子有点不清醒了，给整错了
=> fix: optimize the way to find selectQuality for play ver.

.github/workflows/PR.yml, .github/workflows/android.yml
v3 版本的 `actions/upload-artifact` 和 `actions/download-artifact` 已被弃用： https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
替换为v4版本。
在fork测试了两个actions
- [Android CI](https://github.com/SlowpokeFisher/BiliRoaming/actions/runs/13349579134)
- [PR Build](https://github.com/SlowpokeFisher/BiliRoaming/actions/runs/13349516573)
=> fix: update actions/upload-artifact to v4
